import { Metadata } from "next";
import { Source_Sans_3 } from "next/font/google";
import "./globals.css";
const ss3 = Source_Sans_3({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Admin Signin | Tenelos",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={ss3.className}>{children}</body>
    </html>
  );
}
